### ISSUE TITLE
Migrate project to start using testcontainers

### ISSUE THREAD

**Issue by lfgcampos** [AxonFramework/extension-mongo#35]
### Enhancement Description

Currently, the project relies on [flapdoodle.embed.mongo](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo). The idea is to migrate this dependency to start using [testcontainers](https://www.testcontainers.org/modules/databases/mongodb).

### Current Behaviour

Dependency on `flapdoodle.embed.mongo`.

### Wanted Behaviour

No dependency on `flapdoodle.embed.mongo`.
Added dependency on `testcontainers.mongodb`.
Refactor [MongoLauncher](https://github.com/AxonFramework/extension-mongo/blob/master/mongo/src/test/java/org/axonframework/extensions/mongo/utils/MongoLauncher.java) to rely on `testcontainers.mongodb`.

**Comment by smcvb** [comment]
Let's pair this guy up with #23 (upgrading the `maven-surefire-plugin` version) and #40 (upgrading the `axon` version). Both these PR's seem them break due to the way testing is set up. If we're going to adjust this any how, let's gang up on the other issues around that topic too to safe time.

**Comment by smcvb** [comment]
Changed this issue to a must, due to the shift from TravisCI to GitHub Actions (GHA). During the move it would be beneficial no longer to rely on added services during the build process, as that simplifies the GHA scripts.
