### ISSUE TITLE
Mongo tracking token does not advance when batch size is smaller than total event count during a period of time

### ISSUE THREAD

**Issue by sauliusmasnauskas** [AxonFramework/extension-mongo#6]
This happens for Mongo tracking tokens when using the `DocumentPerCommitStorageStrategy`, [this method is the culprit](https://github.com/AxonFramework/AxonFramework/blob/94bfdb75f4bbf8a20bc39e9cc1261867d23c4d94/mongo/src/main/java/org/axonframework/mongo/eventsourcing/eventstore/AbstractMongoEventStorageStrategy.java#L153).

When events are produced in high quantities, such that the last tracked timestamp minus look-back duration returns an equal or greater number of events than the set batch size, the token never advances and gets stuck in an endless loop. Therefore, event processors never handle newer events.

The event identifier `$nin` [filtering](https://github.com/AxonFramework/AxonFramework/blob/94bfdb75f4bbf8a20bc39e9cc1261867d23c4d94/mongo/src/main/java/org/axonframework/mongo/eventsourcing/eventstore/AbstractMongoEventStorageStrategy.java#L164) does not work for `DocumentPerCommitStorageStrategy` because the events are nested in an array, whereas the filtering is done on the root document. So, even when the events are already known, the same documents are returned. 

This issue is bound to happen if a system is producing many events. In my particular case, there are times when more than 3000 events are saved to MongoDB per second. With the default batch size and look-back time, which are 100 and 1 second respectively, tracking tokens aren't usable as they always get stuck. 

Setting the batch size larger and the look-back time shorter is a workaround for this issue. However, large batch sizes require much more RAM and a short look-back times might "lose" and event if a command handler was lagging behind.

**Comment by abuijze** [comment]
This issue seems to have been fixed as part of another issue, as the code currently uses `cursor.batchSize`, rather than `cursor.limit`.
Marking as duplicate.
