### ISSUE TITLE
Not right order of events during read by findTrackedEvents 

### ISSUE THREAD

**Issue by shtanganet** [AxonFramework/extension-mongo#69]
we have events in next inserted order (generated by command handler line by line of course):
```
{ 
    "_id" : ObjectId("6058ba8e760a705e7d51436c"), 
    "aggregateIdentifier" : "121eb099-3503-4521-80fa-2e0d24a8ce86", 
    "type" : "FinanceOrderAggregate", 
    "sequenceNumber" : NumberLong(66), 
    "timestamp" : "2021-03-22T15:41:02.1019Z", 
    "payloadType" : "...data.access.persistence.axon.event.order.FinanceOrderTaxDeletedEvent", 
},
...
{ 
    "_id" : ObjectId("6058ba8e760a705e7d514372"), 
    "aggregateIdentifier" : "121eb099-3503-4521-80fa-2e0d24a8ce86", 
    "type" : "FinanceOrderAggregate", 
    "sequenceNumber" : NumberLong(72), 
    "timestamp" : "2021-03-22T15:41:02.101944Z", 
    "payloadType" : "....data.access.persistence.axon.event.order.FinanceOrderTaxCreatedEvent", 
}
```

and during [findTrackedEvents](https://github.com/AxonFramework/extension-mongo/blob/master/mongo/src/main/java/org/axonframework/extensions/mongo/eventsourcing/eventstore/AbstractMongoEventStorageStrategy.java#L178) we have next problem:

as ordering of received events by **timestamp, sequenceNumber** and timestamp is string, value "2021-03-22T15:41:02.1019Z" will be greater then "2021-03-22T15:41:02.101944Z".

as result we have handled events in order [72, 66] , not in [66, 72] and got wrong cqrs state.

**Comment by shtanganet** [comment]
after investigation, the problem is found in org.axonframework.common.DateTimeUtils.formatInstant

little test:
sout("from util: " + DateTimeUtils.formatInstant(Instant.parse("2021-03-22T15:41:02.101900Z")));
sout("from util: " + DateTimeUtils.formatInstant(Instant.parse("2021-03-22T15:41:02.101911Z")));
sout("from util: " + DateTimeUtils.formatInstant(Instant.parse("2021-03-22T15:41:02.1019Z")));
sout("simple toString: " +  Instant.parse("2021-03-22T15:41:02.101900Z").toString());
sout("simple toString: " + Instant.parse("2021-03-22T15:41:02.101911Z").toString());
sout("simple toString  " + Instant.parse("2021-03-22T15:41:02.1019Z").toString());

from util: 2021-03-22T15:41:02.1019Z
from util: 2021-03-22T15:41:02.101911Z
from util: 2021-03-22T15:41:02.1019Z
------------------
simple toString: 2021-03-22T15:41:02.101900Z
simple toString: 2021-03-22T15:41:02.101911Z
simple toString  2021-03-22T15:41:02.101900Z

**Comment by smcvb** [comment]
Firstly, thanks for filing this issue with us, and spotting the likely culprit.
The original post you shared already points out there's a discrepancy with the formated time between the two events, which causes the ordering issue as you've noted.
I am sorry for any inconvenience this might have caused on your end, @shtanganet.

For completion sake, would you be able to also provide the Axon Framework (AF) and Mongo Extension (ME) versions you are using?
This might help others to uncover the problem if they encounter this, as well as that it better guides us on where (e.g. branch or version) to fix this.
For the time being, I assume you are using the latest versions of AF and ME.
As the `DateTimeUtils` belongs to AF, I will add the provided test case to the `DateTimeUtils` class.

Lastly, I will move the issue to the Axon Framework repository, as it's a AF utility causing the issue and not the Mongo Extension.

**Comment by smcvb** [comment]
Issue moved to [AxonFramework/AxonFramework #1749](https://github.com/AxonFramework/AxonFramework/issues/1749) via [**ZenHub**](https://www.zenhub.com/)
